id: P64484476
initial_creation_type: input
source_metadata:
  title: Taking Refuge Series
  language: en
  description: 'Texts related to the practice of taking refuge (skyabs ''gro):'
  volume:
    332464153eea45619a7e686ecf2b7534:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    ad0403c75fc949a389f66b58de27bc03:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Practices
    5c792ce72e864870b1bd02b6425e791a:
      title: The Fourfold 'Manam' Refuge
      parent: Practices
    dfd839968cbe493aad0220fbd68a6829:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    a4e384c297ad45118b4443675feafc2d:
      title: The Outer, Inner and Secret Refuge Practice of the Mahāsiddha Thangtong
        Gyalpo
      parent: Practices
    526c165a1c1648428d3df3f53ce12505:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    a2f5fe6101ea4355809739f189d38e40:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
created_at: '2022-03-01T06:01:31.577060'
last_modified_at: '2022-03-01T06:01:31.577066'
